spring:
  datasource:
    url: jdbc:mysql://localhost:3306/info_search
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:sqlserver://localhost:1433; DatabaseName=DatabaseFinal
    #username: root
    #password: bdd4748415
    #driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

    redis:
        # Redis数据库索引（默认为0）    
      database: 0
        # Redis服务器地址
      host: localhost
        # Redis服务器连接端口
      port: 6379
        # Redis服务器连接密码（默认为空）
      password:
        # 连接池最大连接数（使用负值表示没有限制）
      pool.max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
      pool.max-wait: -1
        # 连接池中的最大空闲连接
      pool.max-idle: 8
        # 连接池中的最小空闲连接
      pool.min-idle: 0
        # 连接超时时间（毫秒)
      timeout: 1000
  servlet:
    multipart:
      #上传文件总的最大值
      max-request-size: 10MB
      max-file-size: 10MB
    session:
      timeout: 30*60